### ISSUE TITLE
Update check fails on Ubuntu

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#172]
<img width="1920" alt="screen shot 2015-09-05 at 9 17 41 am" src="https://cloud.githubusercontent.com/assets/1499476/9699384/147be1ae-53af-11e5-9104-c3e98faa3c84.png">

Once this is fixed, I say we push 0.0.5 :smiley:

**Comment by yrsegal** [comment]
Needs more info

**Comment by sdaitzman** [comment]
What other info would help? (Did you see the screenshot?)

**Comment by yrsegal** [comment]
plz test

**Comment by yrsegal** [comment]
if it fails, please run 
`import ssl; dir(ssl)`
in python3 and give me the output

**Comment by sdaitzman** [comment]
it's broken in a different way now:

<img width="1175" alt="screen shot 2015-09-06 at 12 28 47 pm" src="https://cloud.githubusercontent.com/assets/1499476/9705441/e6c61dee-5492-11e5-89ee-7d4aec76e999.png">

and as ugly text:

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
samuel@samrmbp-ubvm ~> cd ~/LaserQueue/
samuel@samrmbp-ubvm ~/LaserQueue> git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/LaserQueue/LaserQueue
   cc3edb7..56cc688  dev-0.0.5  -> origin/dev-0.0.5
Updating cc3edb7..56cc688
Fast-forward
 scripts/initialize.py | 4 ----
 scripts/util.py       | 5 ++++-
 2 files changed, 4 insertions(+), 5 deletions(-)
samuel@samrmbp-ubvm ~/LaserQueue> ./
./plugins/  (Directory)  ./start.py  (Executable, 5.8kB)  ./www/  (Directory)  
./scripts/  (Directory)  ./start.sh    (Executable, 45B)  
samuel@samrmbp-ubvm ~/LaserQueue> ./start.sh -v -b
Traceback (most recent call last):
  File "./start.py", line 28, in <module>
    from util import *
  File "/home/samuel/LaserQueue/scripts/util.py", line 4, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'
samuel@samrmbp-ubvm ~/LaserQueue> python3
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl; dir(ssl)
['AF_INET', 'ALERT_DESCRIPTION_ACCESS_DENIED', 'ALERT_DESCRIPTION_BAD_CERTIFICATE', 'ALERT_DESCRIPTION_BAD_CERTIFICATE_HASH_VALUE', 'ALERT_DESCRIPTION_BAD_CERTIFICATE_STATUS_RESPONSE', 'ALERT_DESCRIPTION_BAD_RECORD_MAC', 'ALERT_DESCRIPTION_CERTIFICATE_EXPIRED', 'ALERT_DESCRIPTION_CERTIFICATE_REVOKED', 'ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN', 'ALERT_DESCRIPTION_CERTIFICATE_UNOBTAINABLE', 'ALERT_DESCRIPTION_CLOSE_NOTIFY', 'ALERT_DESCRIPTION_DECODE_ERROR', 'ALERT_DESCRIPTION_DECOMPRESSION_FAILURE', 'ALERT_DESCRIPTION_DECRYPT_ERROR', 'ALERT_DESCRIPTION_HANDSHAKE_FAILURE', 'ALERT_DESCRIPTION_ILLEGAL_PARAMETER', 'ALERT_DESCRIPTION_INSUFFICIENT_SECURITY', 'ALERT_DESCRIPTION_INTERNAL_ERROR', 'ALERT_DESCRIPTION_NO_RENEGOTIATION', 'ALERT_DESCRIPTION_PROTOCOL_VERSION', 'ALERT_DESCRIPTION_RECORD_OVERFLOW', 'ALERT_DESCRIPTION_UNEXPECTED_MESSAGE', 'ALERT_DESCRIPTION_UNKNOWN_CA', 'ALERT_DESCRIPTION_UNKNOWN_PSK_IDENTITY', 'ALERT_DESCRIPTION_UNRECOGNIZED_NAME', 'ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE', 'ALERT_DESCRIPTION_UNSUPPORTED_EXTENSION', 'ALERT_DESCRIPTION_USER_CANCELLED', 'CERT_NONE', 'CERT_OPTIONAL', 'CERT_REQUIRED', 'CHANNEL_BINDING_TYPES', 'CertificateError', 'DER_cert_to_PEM_cert', 'DefaultVerifyPaths', 'HAS_ECDH', 'HAS_NPN', 'HAS_SNI', 'OPENSSL_VERSION', 'OPENSSL_VERSION_INFO', 'OPENSSL_VERSION_NUMBER', 'OP_ALL', 'OP_CIPHER_SERVER_PREFERENCE', 'OP_NO_COMPRESSION', 'OP_NO_SSLv2', 'OP_NO_SSLv3', 'OP_NO_TLSv1', 'OP_NO_TLSv1_1', 'OP_NO_TLSv1_2', 'OP_SINGLE_DH_USE', 'OP_SINGLE_ECDH_USE', 'PEM_FOOTER', 'PEM_HEADER', 'PEM_cert_to_DER_cert', 'PROTOCOL_SSLv23', 'PROTOCOL_SSLv3', 'PROTOCOL_TLSv1', 'PROTOCOL_TLSv1_1', 'PROTOCOL_TLSv1_2', 'Purpose', 'RAND_add', 'RAND_bytes', 'RAND_egd', 'RAND_pseudo_bytes', 'RAND_status', 'SOCK_STREAM', 'SOL_SOCKET', 'SO_TYPE', 'SSLContext', 'SSLEOFError', 'SSLError', 'SSLSocket', 'SSLSyscallError', 'SSLWantReadError', 'SSLWantWriteError', 'SSLZeroReturnError', 'SSL_ERROR_EOF', 'SSL_ERROR_INVALID_ERROR_CODE', 'SSL_ERROR_SSL', 'SSL_ERROR_SYSCALL', 'SSL_ERROR_WANT_CONNECT', 'SSL_ERROR_WANT_READ', 'SSL_ERROR_WANT_WRITE', 'SSL_ERROR_WANT_X509_LOOKUP', 'SSL_ERROR_ZERO_RETURN', 'VERIFY_CRL_CHECK_CHAIN', 'VERIFY_CRL_CHECK_LEAF', 'VERIFY_DEFAULT', 'VERIFY_X509_STRICT', '_ASN1Object', '_DEFAULT_CIPHERS', '_Enum', '_OPENSSL_API_VERSION', '_PROTOCOL_NAMES', '_RESTRICTED_SERVER_CIPHERS', '_SSLContext', '_SSLv2_IF_EXISTS', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_create_stdlib_context', '_dnsname_match', '_import_symbols', '_nid2obj', '_ssl', '_txt2obj', 'base64', 'cert_time_to_seconds', 'create_connection', 'create_default_context', 'errno', 'get_default_verify_paths', 'get_protocol_name', 'get_server_certificate', 'match_hostname', 'namedtuple', 'os', 're', 'socket', 'socket_error', 'sys', 'textwrap', 'wrap_socket']
>>> 
samuel@samrmbp-ubvm ~/LaserQueue>
```

**Comment by yrsegal** [comment]
it doesn't appear there's an easy (or even feasable) way to do this past 2.7.8 on ubuntu. :/ I'll just warn people in the log.

**Comment by sdaitzman** [comment]
https://asciinema.org/a/2vmf04m36i0wl9pnosgtclggu

**Comment by yrsegal** [comment]
yep, log warn it is.

**Comment by yrsegal** [comment]
update check now fails gracefully with pointers on how to check for updates. good enough, since https seems to hate working on ubuntu.
